sudo: required
services:
  - docker

before_install:
  - docker build -t henrihila/docker-react -f Dockerfile.dev .

script:
  # - docker run henrihila/docker-react npm run test -- --coverage
  - docker run -e CI=true henrihila/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-373254370819"
  bucker_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"